#########################################
### ### Teilen's Sway Config file ### ###
#########################################

# Variables principales
set $cgroup systemd-run --user --scope --slice=app.slice --collect --quiet --unit="app-$(uuidgen)" --
set $browser helium-browser-bin
set $AppMenu rofi -show drun
set $fileExplorer nemo
set $music ~/.config/sway/scripts/rofi_music
set $colorpicker ~/.config/sway/scripts/colorpicker
