######################
### AUTO-DÉMARRAGE ###
######################
exec swaybg -i /usr/share/sway/wall1.jpg -m fill
### Presse-papiers ###
exec wl-paste --type text --watch cliphist store
exec wl-paste --type images --watch cliphist store

### Notifications center ###
exec swaync
# Enables inhibit_idle when playing audio
exec sway-audio-idle-inhibit

### Portails XDG ( but seems useless on fedora, so i comment that ) ###
#exec --no-startup-id dbus-update-activation-environment --all
#exec /usr/libexec/xdg-desktop-portal-wlr &
#exec /usr/libexec/xdg-desktop-portal-gnome &
#exec /usr/libexec/xdg-desktop-portal-gtk &
